name: CI

on:
  pull_request:
    branches: [ next ]
  workflow_dispatch:

# Cancel in-progress runs of this workflow.
# See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check constraints
        run: yarn constraints

      - name: Install dependencies
        run: yarn install --immutable

      - name: Linting
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Build packages
        run: yarn build

