name: Deploy Nightly Release

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  publish:
    if: github.repository == 'lunchbreakdev/lunchbreak' # prevent running on forks
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: yarn install --immutable

      - name: Build
        run: yarn build

      # Prepares a nightly release version of any package with pending changesets
      # Pre-mode is exited if case we're in it, otherwise it has no effect
      - name: Prepare nightly release
        run: |
          yarn changeset pre exit || true
          yarn changeset version --snapshot nightly

      # Publishes the nightly release to npm, by using tag we make sure the release is
      # not flagged as the latest release, which means that people will not get this
      # version of the package unless requested explicitly
      - name: Publish nightly release
        run: |
          yarn config set -H 'npmAuthToken' "${{secrets.NPM_TOKEN}}"
          yarn workspaces foreach -p -j 10 -v --no-private npm publish --access public --tolerate-republish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

